from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 540)
        MainWindow.setFixedSize(960, 540)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainImage = QtWidgets.QLabel(self.centralwidget)
        self.MainImage.setGeometry(QtCore.QRect(0, 0, 960, 540))
        self.MainImage.setText("")
        self.MainImage.setPixmap(QtGui.QPixmap("Data/Images/PyTutorial_Reg1.png"))
        self.MainImage.setObjectName("MainImage")
        self.regist = QtWidgets.QPushButton(self.centralwidget)
        self.regist.setGeometry(QtCore.QRect(270, 407, 111, 32))
        self.regist.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.regist.setStyleSheet("background-color: rgba(0, 0, 0, 0)")
        self.regist.setText("")
        self.regist.setObjectName("regist")
        self.Edit_nickname = QtWidgets.QLineEdit(self.centralwidget)
        self.Edit_nickname.setGeometry(QtCore.QRect(270, 237, 191, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.Edit_nickname.setFont(font)
        self.Edit_nickname.setStyleSheet("background-color: rgba(0, 0, 0, 0)")
        self.Edit_nickname.setFrame(False)
        self.Edit_nickname.setObjectName("Edit_nickname")
        self.Edit_email = QtWidgets.QLineEdit(self.centralwidget)
        self.Edit_email.setGeometry(QtCore.QRect(270, 272, 191, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.Edit_email.setFont(font)
        self.Edit_email.setStyleSheet("background-color: rgba(0, 0, 0, 0)")
        self.Edit_email.setFrame(False)
        self.Edit_email.setObjectName("Edit_email")
        self.Edit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.Edit_password.setGeometry(QtCore.QRect(270, 308, 191, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.Edit_password.setFont(font)
        self.Edit_password.setStyleSheet("background-color: rgba(0, 0, 0, 0)")
        self.Edit_password.setFrame(False)
        self.Edit_password.setObjectName("Edit_password")
        self.Edit_password_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Edit_password_2.setGeometry(QtCore.QRect(270, 343, 191, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.Edit_password_2.setFont(font)
        self.Edit_password_2.setStyleSheet("background-color: rgba(0, 0, 0, 0)")
        self.Edit_password_2.setFrame(False)
        self.Edit_password_2.setObjectName("Edit_password_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.Edit_nickname.setPlaceholderText(_translate("MainWindow", "Nickname"))
        self.Edit_email.setPlaceholderText(_translate("MainWindow", "E-mail"))
        self.Edit_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.Edit_password_2.setPlaceholderText(_translate("MainWindow", "Password"))
        MainWindow.setWindowTitle(_translate("MainWindow", "PyTorial"))
