from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 540)
        MainWindow.setFixedSize(980, 540)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Main_img = QtWidgets.QLabel(self.centralwidget)
        self.Main_img.setGeometry(QtCore.QRect(0, 0, 980, 540))
        self.Main_img.setText("")
        self.Main_img.setPixmap(QtGui.QPixmap("Data/Images/PyTutorial_Courses_1.png"))
        self.Main_img.setObjectName("Main_img")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 980, 540))
        self.scrollArea.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 978, 538))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.Up_img = QtWidgets.QLabel(self.centralwidget)
        self.Up_img.setGeometry(QtCore.QRect(0, 0, 980, 89))
        self.Up_img.setText("")
        self.Up_img.setPixmap(QtGui.QPixmap("Data/Images/PyTutorial_Courses_2.png"))
        self.Up_img.setObjectName("Up_img")
        self.Name_txt = QtWidgets.QLabel(self.centralwidget)
        self.Name_txt.setGeometry(QtCore.QRect(30, 17, 600, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Name_txt.setFont(font)
        self.Name_txt.setObjectName("Name_txt")
        self.Back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Back_btn.setGeometry(QtCore.QRect(830, 17, 117, 33))
        self.Back_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Back_btn.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.Back_btn.setText("")
        self.Back_btn.setObjectName("Back_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyTorial"))
        self.Name_txt.setText(_translate("MainWindow", "Course_name"))
